### ISSUE TITLE
:sparkles:  초기 RD 설계 및 기획

### ISSUE THREAD

**Issue by Hyunja27** [PPiing/PPoong#1]
## 필요 기능
- ERD 설계 및 기획

## 연관 기능
- 서비스 전반

**Comment by jinbekim** [comment]
참고링크 : https://www.erdcloud.com/d/FmWNriGfyGqmgn3FB

**Comment by muingY** [comment]
erd cloud 팀 링크: https://www.erdcloud.com/team/2zCtg97yS4x6tDWb7

**Comment by joohongpark** [comment]
https://github.com/PPiing/wiki/tree/main/develop_specification 해당 링크 Wiki에 업데이트 하였습니다.

**Comment by Hyunja27** [comment]
초기 RD 설계 및 기획 완료!
