### ISSUE TITLE
:sparkles: Backend 코드 초기 설정

### ISSUE THREAD

**Issue by joohongpark** [PPiing/PPoong#10]
## 필요 기능
- Nest.js 기반 Backend 코드 초기 설정
- prettier 삭제 및 ESLint 룰 추가

## 연관 기능
- #7

**Comment by jinbekim** [comment]
`.eslintrc.json` 에서 
`    "tsconfigRootDir" : "./", ` 부분에 상대경로로 넣었더니 `tsconfig.json`의 경로를 제대로 찾지 못해서 에러메시지가 뜹니다.
일단 저는 `    "tsconfigRootDir" : "/Users/jinbekim/PPoong/backend", ` 이렇게 바꿔서 에러를 없애긴 했는데,
그냥 `__dir__` 변수를 사용할 수 있는 `js` 파일로 바꾸는건 어떨까요?

**Comment by joohongpark** [comment]
음 일단 FE/BE 파트 모두 ESLint 설정파일은 json 포맷으로 사용하기로 협의하였으니 확장자를 변경한다면  27일 오프라인 미팅 시에 한번 논의해보는게 좋을거 같습니다.
그리고 docker-compose 내에서 개발을 진행한다면 모든 팀원들이 동일한 환경 (컨테이너 내에서의 구동)에서 개발하는 장점이 있어 개발 논의시에 docker-compose 환경 내에서 개발도 진행하는 것으로 알고 있었기 때문에 (이 부분은 정확하지 않습니다. 27일 오프라인 미팅 시에 다시 논의해 보도록 해야 할 듯 합니다.) docker-compose 상에서 개발 테스트를 해보았는데 다소 느린 부분을 제외하면 정상적으로 동작하는것 같습니다.
