### ISSUE TITLE
:bug: 클러스터에서 Docker Compose 구동 에러

### ISSUE THREAD

**Issue by joohongpark** [PPiing/PPoong#29]
## Symptom
- 클러스터에서 Docker Compose 구동 에러
  - 볼륨 마운트 에러로 인한 구동 실패

## Environment (OS / Browser)
- 42 Seoul Cluster PC

## [Optional] Screenshot
<img width="473" alt="image" src="https://user-images.githubusercontent.com/27172454/168240470-aedcccec-eb39-4d80-8e70-27ae1ab62361.png">

## [Optional] Error Case
- 클러스터에서 docker-compose를 실행시킬 때

## [Optional] How To Solve
- 볼륨 마운트 방식을 사용하지 않고 이미지를 빌드 후 구동하는 것으로 수정

**Comment by jinbekim** [comment]
@joohongpark 추가로 url 설정이 잘못된것 같습니다.
<img width="592" alt="image" src="https://user-images.githubusercontent.com/59330110/168300978-23f2cfc2-fba8-4ed6-b7ea-e347ee4dcd8b.png">
