### ISSUE TITLE
:sparkles: 인증방식에 대한 논의

### ISSUE THREAD

**Issue by subin195-09** [PPiing/PPoong#9]
## 필요 기능
- 로그인 인증방식에 대한 논의

## 연관 기능
- JWT vs cookie & session

**Comment by muingY** [comment]
참고: https://doozi316.github.io/web/2021/03/08/WEB32/

**Comment by Hyunja27** [comment]
아쥬 전문적인 피드백! 정말 감사합니다!!

**Comment by joohongpark** [comment]
JWT의 단점
 - 구현을 잘못할 경우 더 취약함
 - JWT는 암호화 하는 키가 노출되면 수습이 불가능하다.
 - JWT는 기본적으로 키 내부에 정보를 가지고 있으므로 JWT 키 자체 정보를 보호하기 힘들다.
 - JWT는 멀티 플랫폼에 장점이 많은데 해닫 프로젝트에서 장점을 챙기기 힘듬
## 결론
Token 사용
